# Generated by Django 3.2.12 on 2022-07-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220718_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='onetoone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.kategori2'),
        ),
    ]
