# Generated by Django 3.2.12 on 2022-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_izlenenler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izlenenler',
            name='izlenen',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sub_category',
            field=models.ManyToManyField(to='movies.Sub_category'),
        ),
    ]
